markdown: kramdown
highlighter: pygments
permalink: /:title/
url: http://qinnn.github.io
name: Qin's page
author: Qin Yc
qq: 949280422
email: y.spring.qin@gmail.com
duoshuo: Qin's page
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 949280422
github: Qinnn
safe: true
paginate: 20


